# 
# DO NOT EDIT -- Generated by testdata/completion/bash_oracle.sh
# 
# bash --version:
# GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
# Copyright (C) 2013 Free Software Foundation, Inc.
# License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
# 
# This is free software; you are free to change and redistribute it.
# There is NO WARRANTY, to the extent permitted by law.
# 
# bash_completion:'
# 
# 601749d5105ea2262290a239cfad4b0a  testdata/completion/bash_completion
# -rw-rw-r-- 1 andy andy 72681 Dec 20 20:40 testdata/completion/bash_completion
# 
CASES = []

case = {}
CASES.append(case)
case["code"] = 'reassemble foo:bar --color=auto\t'
case["COMP_LINE"] = 'reassemble foo:bar --color=auto'
case["COMP_POINT"] = '31'
case["COMP_WORDS"] = ['reassemble', 'foo', ':', 'bar', '--color', '=', 'auto']
case["COMP_CWORD"] = '6'
case["_completion_reassemble_flags"] = [':', 'words', 'cword']
case["words"] = ['reassemble', 'foo:bar', '--color', '=', 'auto']
case["cword"] = '4'

case = {}
CASES.append(case)
case["code"] = 'words foo:bar --color=auto\t'
case["COMP_LINE"] = 'words foo:bar --color=auto'
case["COMP_POINT"] = '26'
case["COMP_WORDS"] = ['words', 'foo', ':', 'bar', '--color', '=', 'auto']
case["COMP_CWORD"] = '6'
case["_completion_words_flags"] = ['cur']
case["cur"] = 'auto'
