"""
prebuilt/NINJA_subgraph.py
"""

from __future__ import print_function

from build import ninja_lib
from build.ninja_lib import log

_ = log


def NinjaGraph(ru):
  n = ru.n

  n.comment('Generated by %s' % __name__)
  n.newline()

  # These files are checked in
  ru.cc_library(
      '//prebuilt/asdl/runtime', ['prebuilt/asdl/runtime.mycpp.cc'])

  ru.cc_library(
      '//prebuilt/frontend/args', ['prebuilt/frontend/args.mycpp.cc'])
