FROM debian:buster-slim

RUN apt-get update 

WORKDIR /app/tmp

# Copy build scripts into the container and run them

COPY soil/deps-apt.sh /app/tmp/soil/deps-apt.sh
RUN soil/deps-apt.sh other-tests

COPY soil/deps-R.sh /app/tmp/soil/deps-R.sh
RUN soil/deps-R.sh other-tests

CMD ["sh", "-c", "echo 'hello from oilshell/soil-other-tests buildkit'"]
