# This image is only for TESTING

FROM debian:buster-slim

RUN apt-get update

WORKDIR /home/uke/tmp

# Copy build scripts into the container and run them

COPY soil/deps-apt.sh /home/uke/tmp/soil/deps-apt.sh
RUN soil/deps-apt.sh layer-for-soil

# Has build-essential and Python build deps, no system Python 3
RUN soil/deps-apt.sh test-image

RUN useradd --create-home uke && chown -R uke /home/uke
USER uke

COPY --chown=uke _cache/Python-3.10.4.tar.xz \
  /home/uke/tmp/_cache/Python-3.10.4.tar.xz

COPY build/common.sh /home/uke/tmp/build/common.sh
COPY soil/deps-tar.sh /home/uke/tmp/soil/deps-tar.sh
RUN soil/deps-tar.sh layer-py3

# Note: reproducing ensurepip failure here?
COPY mycpp/common.sh /home/uke/tmp/mycpp/common.sh
COPY soil/deps-mycpp.sh /home/uke/tmp/soil/deps-mycpp.sh
RUN soil/deps-mycpp.sh layer-mycpp

#RUN soil/deps-mycpp.sh git-clone

#RUN soil/deps-mycpp.sh pip-install

CMD ["sh", "-c", "echo 'hello from oilshell/soil-test-image'"]
