FROM debian:buster-slim

RUN apt-get update

WORKDIR /app/tmp

# Copy build scripts into the container and run them

COPY soil/deps-apt.sh /app/tmp/soil/deps-apt.sh
RUN soil/deps-apt.sh dev-minimal

COPY soil/deps-py.sh /app/tmp/soil/deps-py.sh
RUN soil/deps-py.sh dev-minimal

CMD ["sh", "-c", "echo 'hello from oilshell/soil-dev-minimal buildkit'"]
