FROM debian:buster-slim

RUN apt-get update 

WORKDIR /app/tmp

# Copy build scripts into the container and run them

COPY soil/deps-apt.sh /app/tmp/soil/deps-apt.sh
RUN soil/deps-apt.sh ovm-tarball

COPY soil/deps-tar.sh /app/tmp/soil/deps-tar.sh
RUN soil/deps-tar.sh ovm-tarball

CMD ["sh", "-c", "echo 'hello from oilshell/ovm-tarball buildkit'"]
