"""
osh/NINJA_subgraph.py
"""

from __future__ import print_function

from build.ninja_lib import log

_ = log


def NinjaGraph(ru):
    n = ru.n

    ru.comment('Generated by %s' % __name__)

    n.rule(
        'arith-parse-gen',
        # uses shell style
        command='_bin/shwrap/arith_parse_gen > $out',
        description='arith-parse-gen > $out')

    ru.py_binary('osh/arith_parse_gen.py')

    n.build(['_gen/osh/arith_parse.cc'],
            'arith-parse-gen', [],
            implicit=['_bin/shwrap/arith_parse_gen'])
    n.newline()

    ru.cc_library('//osh/arith_parse',
                  srcs=['_gen/osh/arith_parse.cc'],
                  deps=['//cpp/osh'])
