#!/usr/bin/env bash
#
# Run (parts of) Oils under Python 3.  First, start with the parser.
#
# Usage:
#   test/with-py3.sh <function name>

: ${LIB_OSH=stdlib/osh}
source $LIB_OSH/bash-strict.sh
source $LIB_OSH/task-five.sh

REPO_ROOT=$(cd "$(dirname $0)/.."; pwd)
readonly REPO_ROOT

source build/dev-shell.sh  # python2 and python3

# Like stubs generated by devtools/bin.sh
osh-py3() {
  # Note: NOT using vendor/typing.py
  PYTHONPATH=$REPO_ROOT python3 $REPO_ROOT/bin/oils_for_unix.py osh "$@"
a
}

osh-parse-py3() {
  PYTHONPATH=$REPO_ROOT python3 $REPO_ROOT/bin/osh_parse.py "$@"
}

smoke() {
  #osh-py3 -n -c 'echo hi'

  osh-parse-py3 -c 'echo hi'

  # This no pretty printing
  osh-parse-py3 -n configure

  # Syntax error
  set +o errexit
  osh-parse-py3 -c '( echo zz '
  echo status=$?
  set -o errexit

  echo OK
}

soil-run() {
  smoke
}
 
task-five "$@"
