"""
frontend/NINJA_subgraph.py
"""

from __future__ import print_function

from build import ninja_lib
from build.ninja_lib import log

_ = log


def NinjaGraph(ru):

  ru.comment('Generated by %s' % __name__)

  ru.asdl_library(
      'frontend/types.asdl',
      pretty_print_methods = False)

  ru.asdl_library(
      'frontend/syntax.asdl',
      deps = ['//core/runtime.asdl'])
