#!/bin/sh 
#
# POSIX shell script to install a build oil into the proper directory.
# Distributed with the source tarball.

# NOTE: 'install' is part of coreutils and busybox.

die() {
  echo "FATAL install error: $@" 1>&2
  exit 1
}

# NOTE: The configure step
main() {
  if ! . _build/detected-config.sh; then
    die "Can't find _build/detected-config.h.  Run './configure'"
  fi

  # Now $PREFIX should be defined

  #local exec_filename=oil.ovm-dbg
  local exec_filename=oil.ovm  # Should this go in configure output?

  local dest="$PREFIX/bin/$exec_filename"

  echo "Installing executables in $dest"
  if ! install -v _bin/$exec_filename $dest; then
    die "Couldn't install oil binary"
  fi

  local working_dir=$PWD  # save for later

  cd $PREFIX/bin
  for link in osh oshc; do
    if ! ln -s -f $exec_filename $link; then  # -f to overwrite
      die "Couldn't create $link symlink"
    fi
  done

  #
  # Install man page
  #

  # relevant:
  # https://unix.stackexchange.com/questions/90759/where-should-i-install-manual-pages-in-user-directory
  # https://www.freebsd.org/cgi/man.cgi?query=install

  cd $working_dir

  # e.g. /usr/share/man/man1
  local man_dest="$DATAROOTDIR/man/man1"

  echo "Installing man page osh.1 in $man_dest"
  if ! install -v -d $man_dest; then
    die "Couldn't create $man_dest"
  fi

  # -t to install to a directory and make them, -m so it's not executable
  if ! install -v -m 644 doc/osh.1 $man_dest; then
    die "Couldn't install man page"
  fi
}

main "$@"
