"""
yaks/NINJA_subgraph.py
"""
from __future__ import print_function

from build import ninja_lib
from build.ninja_lib import log, mycpp_binary

_ = log

# TODO: should have dependencies with sh_binary
RULES_PY = 'build/ninja-rules-py.sh'


def NinjaGraph(ru):
    n = ru.n

    ru.comment('Generated by %s' % __name__)

    ru.asdl_library('yaks/yaks.asdl')

    ru.cc_binary('yaks/yaks_runtime_test.cc',
                 deps=['//mycpp/runtime'],
                 matrix=ninja_lib.COMPILERS_VARIANTS)

    mycpp_binary(
        ru,
        'yaks/yaks_main.py',
        matrix=ninja_lib.COMPILERS_VARIANTS + ninja_lib.GC_PERF_VARIANTS,
        deps=[
            '//core/optview',  # TODO: remove this dep
            '//core/runtime.asdl',
            '//core/value.asdl',
            '//cpp/data_lang',
            '//cpp/frontend_match',
            '//data_lang/nil8.asdl',
            '//frontend/consts',
            '//frontend/syntax.asdl',  # TODO: remove this, value.asdl dep
            '//mycpp/runtime',
            '//yaks/yaks.asdl',
        ])

    n.newline()

    ### CUSTOM translation with the COMPILED yaks binary.
    n.rule('yaks',
           command='_bin/cxx-opt/yaks/yaks_main.mycpp cpp $in > $out',
           description='yaks cpp $in > $out')
    n.newline()

    raw_cc = '_gen/yaks/examples/hello_raw.yaks.cc'
    example_cc = '_gen/yaks/examples/hello.yaks.cc'

    n.build(
        [raw_cc],
        'yaks',
        ['yaks/examples/hello.yaks'],
        implicit=['_bin/cxx-opt/yaks/yaks_main.mycpp'],
    )
    n.newline()

    n.build([example_cc],
            'wrap-cc', [raw_cc],
            implicit=[RULES_PY],
            variables=[('main_namespace', 'hello'), ('preamble', '""'),
                       ('main_func', 'main-wrapper')])
    n.newline()

    ru.cc_binary(
        example_cc,
        matrix=ninja_lib.COMPILERS_VARIANTS + ninja_lib.GC_PERF_VARIANTS,
        deps=['//mycpp/runtime'],
    )


# vim: sw=4
