"""
oil_lang/NINJA_subgraph.py
"""

from __future__ import print_function

from build.ninja_lib import log

_ = log


def NinjaGraph(ru):
  ru.comment('Generated by %s' % __name__)

  ru.py_binary('oil_lang/grammar_gen.py')

