from typing import List, Optional, Tuple

def gethostname() -> str: ...
def glob(pat: str) -> List[str]: ...
def fnmatch(pat: str, s: str) -> bool: ...
def regex_first_group_match(regex: str, s: str, pos: int) -> Optional[Tuple[int, int]]: ...
def regex_match(regex: str, s: str) -> Optional[Tuple[str, str, str]]: ...
def wcswidth(s: str) -> int: ...
def get_terminal_width() -> int: ...
def print_time(real: float, user: float, sys: float) -> None: ...
