from typing import List, Optional, Tuple

def gethostname() -> str: ...
def glob(pat: str) -> List[str]: ...
def fnmatch(pat: str, s: str) -> bool: ...
def regex_first_group_match(regex: str, s: str, pos: int) -> Optional[Tuple[int, int]]: ...
