from typing import IO, Any

class File:
  def write(self, s: str) -> None: ...

class Buf(File):
  def write(self, s: str) -> None: ...
  def getvalue(self) -> str: ...

def StdOut() -> File: ...

def log(msg: str, *args: Any) -> None: ...
