"""
asdl/NINJA_subgraph.py
"""

from __future__ import print_function

from build.ninja_lib import log
from build import ninja_lib

_ = log


def NinjaGraph(ru):
  n = ru.n

  n.comment('Generated by %s' % __name__)
  n.newline()

  n.rule('asdl-cpp',
         command='_bin/shwrap/asdl_main $action $asdl_flags $in $out_prefix $debug_mod',
         description='asdl_main $action $asdl_flags $in $out_prefix $debug_mod')
  n.newline()

  # For pretty printing
  ru.asdl_library('asdl/hnode.asdl', pretty_print_methods=False)

  # For unit tests
  ru.asdl_library('asdl/examples/typed_arith.asdl')

  ru.asdl_library('asdl/examples/demo_lib.asdl')
  ru.asdl_library(
      'asdl/examples/typed_demo.asdl',
      deps = ['//asdl/examples/demo_lib.asdl'])

  ru.cc_binary(
      'asdl/gen_cpp_test.cc',
      deps = [
        '//asdl/examples/typed_arith.asdl',
        '//asdl/examples/typed_demo.asdl',
        '//mycpp/runtime',
        '//prebuilt/asdl/runtime.mycpp',
      ],
      matrix = ninja_lib.COMPILERS_VARIANTS)

  ru.cc_binary(
      'asdl/gc_test.cc',
      deps = [
        '//asdl/examples/typed_demo.asdl',
        '//mycpp/runtime',
        '//prebuilt/asdl/runtime.mycpp',
      ],
      matrix = ninja_lib.COMPILERS_VARIANTS)
