#!/bin/sh

set -e

t="$(realpath "$(dirname "$0")")"
cd "$t/.."

if [ $# -eq 0 ]
then set -- "$t"/*/
fi

eval 'xargs_py() {' "$(realpath ./xargs.py)" '"$@";' '}'

for test
do
	args="$test/args"
	stdin="$test/stdin"
	stdout="_tmp/$(basename "$test")_stdout"
	eval xargs $(cat "$args") <"$stdin" >"${stdout}_expected"
	rc_expected=$?
	eval xargs_py $(cat "$args") <"$test/stdin" >"${stdout}_actual"
	rc_actual=$?
	if ! cmp -s "${stdout}_expected" "${stdout}_actual"
	then
		echo "!!! $(basename "$test") failed: files differ"
		echo "--- EXPECTED ---"
		cat "${stdout}_expected"
		echo "--- ACTUAL ---"
		cat "${stdout}_actual"
		echo "--------------"
	elif [ $rc_expected != $rc_actual ]
	then
		echo "!!! $(basename "$test") failed: rcs differ"
		echo "EXPECTED=$rc_expected ACTUAL=$rc_actual"
	else
		echo "    $(basename "$test") ok"
	fi
done
