from typing import Tuple

def J8EncodeString(s: str, j8_fallback: int) -> str: ...

def ShellEncodeString(s: str, ysh_fallback: int) -> str: ...

def PartIsUtf8(s: str, start: int, end: int) -> bool: ...

def Utf8DecodeOne(s: str, start: int) -> Tuple[int, int]: ...

def CanOmitQuotes(s: str) -> bool: ...
