# (based on: https://github.com/cachix/install-nix-action readme)
name: "(Nix) toil run-cpp"
on:
  pull_request:
  push:
jobs:
  toil-run-cpp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
        # Enable Nix Flakes
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - run: nix build -L .#toil-run-cpp
